In [1]:
import pandas as pd

In [2]:
#load dataset into dtatframe
ds=pd.read_csv("archive (6).zip")
ds

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
#display first 10 rows
ds.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [4]:
#unique species 
ds['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
#count flowers in each species
ds['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
#avg petal length for each species
ds['petal_length'].mean()

np.float64(3.758666666666666)

In [12]:
#flower with max sepal length
ds.loc[ds['sepal_length'].idxmax(),'species']

'virginica'

In [16]:
#petal with descending
ds.sort_values('petal_width',ascending=False)

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
109           7.2          3.6           6.1          2.5  virginica
144           6.7          3.3           5.7          2.5  virginica
114           5.8          2.8           5.1          2.4  virginica
140           6.7          3.1           5.6          2.4  virginica
..            ...          ...           ...          ...        ...
13            4.3          3.0           1.1          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
32            5.2          4.1           1.5          0.1     setosa
34            4.9          3.1           1.5          0.1     setosa
9             4.9          3.1           1.5          0.1     setosa

[150 rows x 5 columns]

In [20]:
#flowers with petal_length>5
ds[ds['petal_length']>5]['species']

83     versicolor
100     virginica
101     virginica
102     virginica
103     virginica
104     virginica
105     virginica
107     virginica
108     virginica
109     virginica
110     virginica
111     virginica
112     virginica
114     virginica
115     virginica
116     virginica
117     virginica
118     virginica
120     virginica
122     virginica
124     virginica
125     virginica
128     virginica
129     virginica
130     virginica
131     virginica
132     virginica
133     virginica
134     virginica
135     virginica
136     virginica
137     virginica
139     virginica
140     virginica
141     virginica
142     virginica
143     virginica
144     virginica
145     virginica
147     virginica
148     virginica
149     virginica
Name: species, dtype: object

In [22]:
#add a new column
ds['total_size']=ds['sepal_length']+ds['petal_length']

In [23]:
ds.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'total_size'],
      dtype='object')

In [27]:
#convert petal length column to numpy array
pl=ds['petal_length'].to_numpy()

In [29]:
type(pl)

numpy.ndarray

In [30]:
pl.mean()

np.float64(3.758666666666666)

In [34]:
ds['petal_length'].median()

4.35

In [35]:
pl.std()

np.float64(1.7585291834055212)

In [37]:
pl.max()

np.float64(6.9)

In [38]:
pl.min()

np.float64(1.0)

In [41]:
ds['petal_length'].value_counts(normalize=True)

petal_length
1.5    0.093333
1.4    0.080000
5.1    0.053333
4.5    0.053333
1.6    0.046667
1.3    0.046667
5.6    0.040000
4.7    0.033333
4.9    0.033333
4.0    0.033333
4.2    0.026667
5.0    0.026667
4.4    0.026667
4.8    0.026667
1.7    0.026667
3.9    0.020000
4.6    0.020000
5.7    0.020000
4.1    0.020000
5.5    0.020000
6.1    0.020000
5.8    0.020000
3.3    0.013333
5.4    0.013333
6.7    0.013333
5.3    0.013333
5.9    0.013333
6.0    0.013333
1.2    0.013333
4.3    0.013333
1.9    0.013333
3.5    0.013333
5.2    0.013333
3.0    0.006667
1.1    0.006667
3.7    0.006667
3.8    0.006667
6.6    0.006667
6.3    0.006667
1.0    0.006667
6.9    0.006667
3.6    0.006667
6.4    0.006667
Name: proportion, dtype: float64

In [42]:
import pandas as pd

In [49]:
df=pd.read_csv("netflix_titles.csv (1).zip")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [50]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [51]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [52]:
df[df['type']=='Movie'].shape[0]

6131

In [55]:
df[df['release_year']>2020]['title' ]

1                   Blood & Water
2                       Ganglands
3           Jailbirds New Orleans
4                    Kota Factory
5                   Midnight Mass
                  ...
1468    What Happened to Mr. Cha?
1551                        Hilda
1696                 Polly Pocket
2920                Love Is Blind
8437       The Netflix Afterparty
Name: title, Length: 592, dtype: object

In [56]:
df.loc[df['release_year'].idxmin(), 'title']

'Pioneers: First Women Filmmakers*'

In [60]:
df[df['type']=='Movie']['country'].value_counts()

country
United States                            2058
India                                     893
United Kingdom                            206
Canada                                    122
Spain                                      97
                                         ...
United Kingdom, Russia, United States       1
Paraguay, Argentina                         1
United Kingdom, Malawi                      1
Austria, Iraq, United States                1
United Arab Emirates, Jordan                1
Name: count, Length: 651, dtype: int64

In [61]:
df['director'].value_counts().head(10)

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Suhas Kadav               16
Jay Karas                 14
Cathy Garcia-Molina       13
Martin Scorsese           12
Youssef Chahine           12
Jay Chapman               12
Steven Spielberg          11
Name: count, dtype: int64

In [65]:
df['director'].head()

0    Kirsten Johnson
1                NaN
2    Julien Leclercq
3                NaN
4                NaN
Name: director, dtype: object

In [66]:
df[df['type']=='Movie']['duration']

0        90 min
6        91 min
7       125 min
9       104 min
12      127 min
         ...
8801     96 min
8802    158 min
8804     88 min
8805     88 min
8806    111 min
Name: duration, Length: 6131, dtype: object

In [78]:
df.loc[df['duration'].str.extract('(\d+)').astype(float).idxmax(),'title']

4253    Black Mirror: Bandersnatch
Name: title, dtype: object

In [97]:
df=pd.read_csv("netflix_titles.csv (1).zip")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [98]:
df=df.drop(['show_id','date_added','rating','description'],axis="columns",errors='ignore')
df

,type,title,director,cast,country,release_year,duration,listed_in
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2020,90 min,Documentaries
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021,1 Season,"Docuseries, Reality TV"
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2007,158 min,"Cult Movies, Dramas, Thrillers"
8803,TV Show,Zombie Dumb,NaN,NaN,NaN,2018,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2009,88 min,"Comedies, Horror Movies"
8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2006,88 min,"Children & Family Movies, Comedies"
8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2015,111 min,"Dramas, International Movies, Music & Musicals"

In [99]:
df[df['type']== 'Movie'].sort_values('release_year')

,type,title,director,cast,country,release_year,duration,listed_in
7790,Movie,Prelude to War,Frank Capra,NaN,United States,1942,52 min,"Classic Movies, Documentaries"
8205,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,1942,18 min,"Classic Movies, Documentaries"
8660,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,1943,61 min,"Classic Movies, Documentaries"
8763,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,1943,45 min,Documentaries
8739,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,1943,82 min,Documentaries
...,...,...,...,...,...,...,...,...
1420,Movie,"Crack: Cocaine, Corruption & Conspiracy",Stanley Nelson,NaN,United States,2021,90 min,Documentaries
373,Movie,The Last Mercenary,David Charhon,"Jean-Claude Van Damme, Alban Ivanov, Éric Judo...",NaN,2021,112 min,"Action & Adventure, Comedies, International Mo..."
1424,Movie,Charming,Ross Venokur,"Wilmer Valderrama, Demi Lovato, Sia, Nia Varda...","Canada, United States, Cayman Islands",2021,85 min,"Children & Family Movies, Comedies"
372,Movie,Rurouni Kenshin: The Beginning,Keishi Otomo,"Takeru Satoh, Kasumi Arimura, Issey Takahashi,...",NaN,2021,138 min,"Action & Adventure, International Movies"
394,Movie,African America,Muzi Mthembu,"Phumelele Mthembu, Anthony Goss, Thami Buti, M...",NaN,2021,97 min,"Dramas, Independent Movies, International Movies"

In [102]:
df[df['listed_in'].str.contains('Comedy',na=False)]

,type,title,director,cast,country,release_year,duration,listed_in
278,Movie,Lokillo: Nothing's the Same,Julián Gaviria,Lokillo Florez,Colombia,2021,64 min,Stand-Up Comedy
359,Movie,The Original Kings of Comedy,Spike Lee,"Steve Harvey, D.L. Hughley, Cedric the Enterta...",United States,2000,111 min,Stand-Up Comedy
388,TV Show,Plastic Cup Boyz: Laughing My Mask Off!,"Royale Watkins, Rich Schlansker","Joey Wells, Will 'Spank' Horton, Na'im Lynn",NaN,2021,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies"
400,TV Show,Revelations: The Masters of the Universe: Reve...,NaN,"Kevin Smith, Tiffany Smith, Robert David, Sara...",NaN,2021,1 Season,"Anime Series, Stand-Up Comedy & Talk Shows"
475,Movie,The Stand-Up,Daniel Růžička,"Iva Pazderková, Lukáš Pavlásek, Daniel Čech, P...",NaN,2019,93 min,Stand-Up Comedy
...,...,...,...,...,...,...,...,...
7812,TV Show,Queens of Comedy,NaN,NaN,NaN,2017,1 Season,"International TV Shows, Stand-Up Comedy & Talk..."
7813,TV Show,Queens vs. Kings,NaN,"Varun Thakur, Anu Menon, Rahul Subramanian, Si...",NaN,2018,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies"
7908,TV Show,Russell Peters vs. the World,NaN,Russell Peters,United States,2013,1 Season,"Docuseries, Stand-Up Comedy & Talk Shows"
7909,Movie,Russell Peters: Notorious,Dave Higby,Russell Peters,United States,2013,72 min,Stand-Up Comedy
8437,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,2021,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies"

In [104]:
df['decade']=(df['release_year']//10)*10
df

,type,title,director,cast,country,release_year,duration,listed_in,decade
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2020,90 min,Documentaries,2020
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",2020
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2020
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021,1 Season,"Docuseries, Reality TV",2020
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",2020
...,...,...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2007,158 min,"Cult Movies, Dramas, Thrillers",2000
8803,TV Show,Zombie Dumb,NaN,NaN,NaN,2018,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",2010
8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2009,88 min,"Comedies, Horror Movies",2000
8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2006,88 min,"Children & Family Movies, Comedies",2000
8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2015,111 min,"Dramas, International Movies, Music & Musicals",2010

In [106]:
du=df['duration'].to_numpy()

In [110]:
type(du)

numpy.ndarray